# Generated by Django 3.2.8 on 2021-12-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('expert', models.TextField()),
                ('rating', models.TextField()),
                ('location', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
