# Generated by Django 3.2.8 on 2021-12-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
